name: final_project
version: "1.0"
profile: final_project

model-paths: ["models"]

models:
  +materialized: view
  final_project:
    staging:
      +materialized: view
    mart:
      +materialized: table
